baseurl = "/"
languageCode = "en-us"
title = "Andrea Cirillo"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "about"
    url = "/about/"
    weight = -110
[[menu.main]]
    name = "pubblications"
    url = "/pubblications"
    weight = -100
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = -80
[[menu.main]]
    name = "software"
    url = "/software/"
    weight = -90
[[menu.main]]
    name = "contacts"
    url = "/contacts/"
    weight = -70
[[menu.main]]
    name = "bookstack"
    url = "/bookstack/"
    weight = -80
[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"
    [params.logo]
    url = "aclogo.ico"
    width = 40
    height = 40
    alt = "Logo"

