baseurl = "/post"
languageCode = "en-us"
title = "Un Taccuino"
theme = "hugo-lithium-theme"
disqusShortname = "andreacirillo"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "about"
    url = "/about/"
    weight = -110
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = -80
[[menu.main]]
    name = "contacts"
    url = "/contacts/"
    weight = -70
[[menu.main]]
    name = "bookstack (WIP)"
    url = "https://personalandrea.notion.site/Bookstack-WIP-544d095a8d9e4125bfb722a62e4a05ce"
    weight = -80
[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"
    
    [params.logo]
    url = "aclogo.ico"
    width = 40
    height = 40
    alt = "Logo"

