---
title: "contacts"
toc: false
tags: "contacts"
---

I do not have a general purposes email ( I actually used to have one but it got irredeemably full of spam) but I carefully **crafted three main channels** to get exposed to all relevant and promising opportunities. 

You can find them below:

### Proposals of Blog Post/Speaches

author _at_ andreacirillo.com

### Collaboration proposals

you can use my linkedin profile to get in touch with me for proposals of every kind of collaboration, either requesting to connect or sending inmail messages:
[linkedin profile](https://www.linkedin.com/in/cirilloandrea/)

### interesting stuff to read or watch

you can use one of my twitter profile to refer any interesting link or stuff, even considering that if it is interesting, why shouldn't we share it to everybody?

[twitter profile](https://twitter.com/AndreaCirilloAC)

### comments on packages/issues

I frequently blog about software I have developed. If you have any kind of comment, request of improvement and similar stuff, the best way to submit them is to reach the online github repository of the package and post there your request.

### stay updated on the blog

**subscribe to the mailing list if you want to stay update on my work**
*I will neither spam you nor give your email address to rhid parties. I will just occasionally send one or two emails per month*

 <!-- Begin Mailchimp Signup Form -->
<center>
<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif;width:50%; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://andreacirillo.us18.list-manage.com/subscribe/post?u=ea38207c9143ded9017ecd6bc&amp;id=4421c1bc47" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
<div id="mc_embed_signup_scroll">
<h2>Join the mailing list to stay updated</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div id="mce-responses" class="clear">
<div class="response" id="mce-error-response" style="display:none"></div>
<div class="response" id="mce-success-response" style="display:none"></div>
</div>   

<div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_ea38207c9143ded9017ecd6bc_4421c1bc47" tabindex="-1" value=""></div>
<div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
</div>
</form>
</div>
</center>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';fnames[5]='BIRTHDAY';ftypes[5]='birthday';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
<!--End mc_embed_signup-->

#### disclaimer
In qualità di Affiliato Amazon io ricevo un guadagno dagli acquisti idonei






